// Weight conversion data for all ingredients.
// Values are grams per standard unit. Based on USDA / King Arthur Flour weight charts.
//
// null = skip (spice, herb, negligible, or measured by count only)
// For items measured by lb/oz, we include those conversions too.
// cup/tbsp/tsp are volume; lb/oz are weight (already metric-convertible).

export const WEIGHTS = {
  // ─── A ───
  'acai': { cup: 150 },
  'achiote paste': null,
  'active dry yeast': null,
  'aged cheddar': { cup: 113, oz: 28 },
  'ahi tuna': { oz: 28, lb: 454 },
  'alfredo sauce': { cup: 240 },
  'all-purpose flour': { cup: 120, tbsp: 8, tsp: 3 },
  'allspice': null,
  'almond extract': null,
  'almond flour': { cup: 96, tbsp: 6 },
  'almonds': { cup: 140 },
  'anchovy fillets': null,
  'aonori': null,
  'apple cider vinegar': null,
  'apples': null, // counted
  'artichoke hearts': { cup: 170 },
  'asian pear': null,
  'au jus mix': null,
  'avocado': null,
  'avocado oil': { tbsp: 14, cup: 224 },
  'avocados': null,

  // ─── B ───
  'baby back ribs': { lb: 454 },
  'baby carrots': { cup: 128 },
  'baby spinach': { cup: 30 },
  'bacon': null, // counted by slices
  'baking powder': null,
  'baking soda': null,
  'balsamic vinegar': null,
  'bamboo shoots': { cup: 130 },
  'banana leaves': null,
  'bananas': null,
  'basil': null,
  'basil (dried)': null,
  'basmati rice': { cup: 185 },
  'bay leaves': null,
  'bbq sauce': { tbsp: 17, cup: 270 },
  'bean sprouts': { cup: 104 },
  'beef broth': { cup: 240 },
  'beef bulgogi': { oz: 28, lb: 454 },
  'beef chuck roast': { lb: 454 },
  'beef hot dogs': null,
  'beef ribeye': { lb: 454 },
  'beef short ribs': { lb: 454 },
  'beef sirloin': { lb: 454 },
  'bell peppers': null,
  'berries': { cup: 150 },
  'black beans': { cup: 170 },
  'black olives': { cup: 135 },
  'black pepper': null,
  'blueberries': { cup: 148 },
  'bread': null,
  'bread flour': { cup: 120, tbsp: 8 },
  'breadcrumbs': { cup: 108, tbsp: 7 },
  'breakfast sausage': { oz: 28 },
  'brie cheese': { oz: 28 },
  'brioche buns': null,
  'broccoli': { cup: 91 },
  'broccoli crowns': { cup: 91 },
  'broccoli florets': { cup: 91 },
  'brown sugar': { cup: 220, tbsp: 14 },
  'buffalo sauce': { tbsp: 15 },
  'butter': { cup: 227, tbsp: 14, tsp: 5 },
  'butter croissants': null,
  'butter lettuce': { cup: 55 },
  'butternut squash': { cup: 205 },

  // ─── C ───
  'cabbage': { cup: 89 },
  'caesar dressing': { tbsp: 15 },
  'caesar salad kit': null,
  'cannellini beans': { cup: 179 },
  'capers': null,
  'carrots': null, // counted
  'cashews': { cup: 130 },
  'cayenne pepper': null,
  'celery': null,
  'chai tea': null,
  'cheese ravioli': { cup: 200 },
  'cherry pie filling': { cup: 270 },
  'cherry tomatoes': { cup: 149 },
  'chia seeds': { tbsp: 12 },
  'chicken breasts': { lb: 454 },
  'chicken broth': { cup: 240 },
  'chicken dumplings': null,
  'chicken street tacos kit': null,
  'chicken thighs': { lb: 454 },
  'chicken wings': { lb: 454 },
  'chickpea pasta': { oz: 28 },
  'chili oil': null,
  'chili powder': null,
  'chipotle peppers in adobo': null,
  'chives': null,
  'chocolate chips': { cup: 168 },
  'chocolate shavings': null,
  'cilantro': null,
  'cilantro lime rice': { cup: 200 },
  'cinnamon': null,
  'cinnamon stick': null,
  'clam juice': { cup: 240 },
  'clams': { oz: 28 },
  'coconut flakes': { cup: 80 },
  'coconut milk': { cup: 240 },
  'coconut oil': { tbsp: 14, cup: 218 },
  'coffee': null,
  'coleslaw': { cup: 90 },
  'cooked rice': { cup: 185 },
  'cooking spray': null,
  'coriander': null,
  'corn': { cup: 164 },
  'corn kernels': { cup: 164 },
  'corn syrup': { tbsp: 21, cup: 340 },
  'corn tortillas': null,
  'cornichons': null,
  'cornmeal': { cup: 150, tbsp: 9 },
  'cornstarch': { tbsp: 8, cup: 128 },
  'cornstarch slurry': null,
  'cotija cheese': { cup: 113, oz: 28 },
  'crab meat': { oz: 28 },
  'crackers': null,
  'cream cheese': { cup: 232, oz: 28, tbsp: 14.5 },
  'crusty bread': null,
  'cucumber': null,
  'cumin': null,

  // ─── D ───
  'dark brown sugar': { cup: 220, tbsp: 14 },
  'dark chocolate': { oz: 28 },
  'dark soy sauce': { tbsp: 18 },
  'dashi': { cup: 240 },
  'dashi broth': { cup: 240 },
  'deli mustard': null,
  'diced green chiles': { tbsp: 10 },
  'diced tomatoes': { cup: 240 },
  'dijon mustard': null,
  'dill': null,
  'dill pickles': null,
  'dried ancho chiles': null,
  'dried cranberries': { cup: 120 },
  'dried guajillo chiles': null,
  'dried red chilies': null,
  'dry mustard powder': null,
  'dry red wine': { cup: 240 },
  'dry white wine': { cup: 240 },

  // ─── E ───
  'edamame': { cup: 155 },
  'egg noodles': { oz: 28 },
  'egg roll wrappers': null,
  'egg wash': null,
  'egg yolk': null,
  'eggs': null,
  'elbow macaroni': { oz: 28, cup: 115 },
  'enchilada sauce': { cup: 250 },
  'english mustard': null,
  'espresso powder': null,
  'evaporated milk': { cup: 252 },
  'everything bagels': null,

  // ─── F ───
  'feta cheese': { cup: 150, oz: 28 },
  'fig jam or preserves': { tbsp: 20 },
  'fine sea salt': null,
  'fish cake': null,
  'fish sauce': null,
  'five-spice powder': null,
  'flaky salt': null,
  'flaky sea salt': null,
  'flour': { cup: 120, tbsp: 8 },
  'flour tortillas': null,
  'french baguettes': { oz: 28 },
  'fresh mozzarella': { oz: 28 },
  'fried shallots': null,
  'fukujinzuke': null,

  // ─── G ───
  'garam masala': null,
  'garlic': null,
  'garlic powder': null,
  'giardiniera': null,
  'ginger': null,
  'gochugaru': null,
  'gochujang': { tbsp: 18 },
  'gouda': { oz: 28 },
  'graham crackers': null,
  'granola': { cup: 110 },
  'granulated sugar': { cup: 200, tbsp: 12, tsp: 4 },
  'grape tomatoes': { cup: 149 },
  'grated parmesan': { cup: 100, tbsp: 5 },
  'great northern beans': { cup: 179 },
  'greek yogurt': { cup: 245 },
  'green bell pepper': null,
  'green cabbage': { cup: 89 },
  'green curry paste': { tbsp: 16 },
  'green leaf lettuce': { cup: 36 },
  'green onions': null,
  'ground beef': { lb: 454, oz: 28 },
  'ground cardamom': null,
  'ground chicken': { lb: 454 },
  'ground cinnamon': null,
  'ground cloves': null,
  'ground cumin': null,
  'ground ginger': null,
  'ground lamb': { lb: 454 },
  'ground nutmeg': null,
  'ground pork': { lb: 454 },
  'ground turkey': { lb: 454 },
  'ground turmeric': null,
  'gruyere cheese': { oz: 28, cup: 108 },
  'gyro meal kit': null,

  // ─── H ───
  'habanero salsa': { tbsp: 16 },
  'ham': { oz: 28 },
  'hard-boiled egg': null,
  'hash browns': { cup: 170 },
  'hearts of romaine': { cup: 47 },
  'heavy cream': { cup: 240, tbsp: 15 },
  'hoagie rolls': null,
  'hoisin sauce': { tbsp: 19 },
  'honey': { cup: 340, tbsp: 21 },
  'hot dog buns': null,
  'hot fudge sauce': { tbsp: 20 },
  'hot sauce': null,
  'hummus': { tbsp: 15 },

  // ─── I ───
  'ice': null,
  'instant yeast': null,
  'italian breadcrumbs': { cup: 108 },
  'italian dressing mix': null,
  'italian sausage': null,
  'italian seasoning': null,

  // ─── J ───
  'jalapeno': null,
  'jalapeno peppers': null,
  'japanese curry roux': null,
  'japanese mayonnaise': { tbsp: 14 },
  'jasmine rice': { cup: 185 },

  // ─── K ───
  'kalamata olives': { cup: 135 },
  'katsuobushi': null,
  'ketchup': { tbsp: 17 },
  'kewpie mayonnaise': { tbsp: 14 },
  'kidney beans': { cup: 177 },
  'kimchi': { cup: 150 },
  'korean pear': null,
  'korean rice cakes': { cup: 200 },
  'kosher salt': null,

  // ─── L ───
  'lasagna noodles': { oz: 28 },
  'lemon': null,
  'lemon juice': { tbsp: 15 },
  'lemon wedges': null,
  'lemons': null,
  'lettuce': { cup: 47 },
  'lime': null,
  'lime juice': { tbsp: 15 },
  'lime wedges': null,
  'limes': null,

  // ─── M ───
  'manchego cheese': { oz: 28 },
  'mango': { cup: 165 },
  'maple syrup': { cup: 315, tbsp: 20 },
  'marinade': null,
  'marinara sauce': { cup: 250 },
  'marsala wine': { cup: 240 },
  'marshmallows': null,
  'mayonnaise': { cup: 220, tbsp: 14 },
  'meatloaf': { oz: 28 },
  'mexican blend cheese': { cup: 113 },
  'mexican oregano': null,
  'milk': { cup: 244 },
  'mint leaves': null,
  'mirin': { tbsp: 18 },
  'mixed berries': { cup: 150 },
  'mixed nuts': { cup: 132 },
  'mixed olives': { cup: 135 },
  'mixed vegetables': { cup: 150 },
  'monterey jack cheese': { cup: 113, oz: 28 },
  'mushrooms': { cup: 70 },

  // ─── N ───
  'napa cabbage': { cup: 76 },
  'neutral oil': { tbsp: 14 },
  'nori': null,
  'nutmeg': null,

  // ─── O ───
  'octopus': { oz: 28 },
  'old bay seasoning': null,
  'olive oil': { tbsp: 14, cup: 216 },
  'onion': null,
  'onion powder': null,
  'orange juice': { cup: 248 },
  'orange zest': null,
  'oregano': null,
  'original naan': null,
  'orzo': { cup: 180, oz: 28 },
  'oyster sauce': { tbsp: 18 },

  // ─── P ───
  'panko breadcrumbs': { cup: 60 },
  'paprika': null,
  'parmesan rind': null,
  'parmigiano reggiano': { cup: 100, oz: 28 },
  'parsley': null,
  'pasta': { oz: 28, cup: 115 },
  'peanut butter': { cup: 258, tbsp: 16 },
  'peas and carrots': { cup: 160 },
  'pecans': { cup: 109 },
  'penne pasta': { oz: 28, cup: 115 },
  'pepperoncini peppers': null,
  'pepperoni': { oz: 28 },
  'pesto': { tbsp: 16 },
  'phyllo dough': null,
  'pickled ginger': null,
  'pickled jalapenos': null,
  'pickled red onions': null,
  'pico de gallo': { cup: 175 },
  'pie crust': null,
  'pita bread': null,
  'pita chips': { oz: 28 },
  'pizza dough': { oz: 28 },
  'pizza sauce': { cup: 250 },
  'poblano pepper': null,
  'pork belly': { lb: 454 },
  'pork shoulder': { lb: 454 },
  'potato starch': { tbsp: 10, cup: 160 },
  'powdered sugar': { cup: 120, tbsp: 8 },
  'prosciutto': { oz: 28 },
  'protein pancake mix': { cup: 120 },
  'provolone cheese': { oz: 28 },
  'puff pastry': null,
  'pumpkin puree': { cup: 245 },

  // ─── Q ───
  'quinoa': { cup: 185 },

  // ─── R ───
  'radishes': { cup: 116 },
  'raisins': { cup: 145 },
  'ranch dressing': { tbsp: 15 },
  'ranch seasoning mix': null,
  'raw shrimp': { oz: 28, lb: 454 },
  'red bell pepper': null,
  'red cabbage': { cup: 89 },
  'red enchilada sauce': { cup: 250 },
  'red grapes': { cup: 151 },
  'red onion': null,
  'red pepper flakes': null,
  'red thai chili': null,
  'red wine vinegar': null,
  'refried beans': { cup: 252 },
  'rice krispies cereal': { cup: 28 },
  'rice noodles': { oz: 28 },
  'rice vinegar': null,
  'rice wine': null,
  'ricotta cheese': { cup: 246 },
  'roasted corn': { cup: 164 },
  'roasted seaweed': null,
  'rolled oats': { cup: 80 },
  'roma tomatoes': null,
  'romaine hearts': { cup: 47 },
  'rosemary': null,
  'rotini pasta': { oz: 28, cup: 115 },
  'rotisserie chicken': { oz: 28, lb: 454 },
  'russet potatoes': null,

  // ─── S ───
  'saffron': null,
  'sage': null,
  'sake': null,
  'salami': { oz: 28 },
  'salmon fillets': { oz: 28, lb: 454 },
  'salsa': { cup: 260, tbsp: 16 },
  'salsa verde': { cup: 260, tbsp: 16 },
  'salt': null,
  'salt and pepper': null,
  'salt and white pepper': null,
  'salted butter': { cup: 227, tbsp: 14 },
  'sauerkraut': { cup: 142 },
  'scallions': null,
  'sea scallops': { oz: 28 },
  'semi-sweet chocolate chips': { cup: 168 },
  'sesame oil': null,
  'sesame seeds': { tbsp: 9 },
  'shaoxing wine': null,
  'sharp cheddar': { cup: 113, oz: 28 },
  'shichimi togarashi': null,
  'shredded cheddar': { cup: 113 },
  'shredded cheese': { cup: 113 },
  'shredded mozzarella': { cup: 113 },
  'shredded parmesan': { cup: 100, tbsp: 5 },
  'smoked paprika': null,
  'soba noodles': { oz: 28 },
  'soup dumplings': null,
  'sour cream': { cup: 230, tbsp: 14 },
  'soy sauce': { tbsp: 18 },
  'spaghetti': { oz: 28 },
  'sparkling water': null,
  'spinach': { cup: 30 },
  'spring mix': { cup: 30 },
  'sriracha': null,
  'sriracha mayo': { tbsp: 14 },
  'stir-fry vegetable blend': { cup: 140 },
  'strawberries': { cup: 152 },
  'stuffed salmon': { oz: 28 },
  'sugar': { cup: 200, tbsp: 12, tsp: 4 },
  'sun-dried tomatoes': { cup: 110 },
  'sunflower seeds': { cup: 140 },
  'sweet chili sauce': { tbsp: 20 },
  'sweet corn': { cup: 164 },
  'sweet potato noodles': { oz: 28 },
  'sweet relish': { tbsp: 15 },
  'sweetened condensed milk': { cup: 306, tbsp: 19 },
  'swiss or gruyere cheese': { oz: 28 },

  // ─── T ───
  'taco seasoning': null,
  'takoyaki sauce': null,
  'tamarind paste': null,
  'tart shells': null,
  'tartar sauce': { tbsp: 16 },
  'tenkasu': null,
  'thai basil': null,
  'thai red curry paste': { tbsp: 16 },
  'three berry blend': { cup: 150 },
  'thyme': null,
  'tilapia fillets': { oz: 28, lb: 454 },
  'tomato': null,
  'tomato paste': { tbsp: 16 },
  'tomato sauce': { cup: 245 },
  'tomatoes': null,
  'tortilla chips': { oz: 28 },
  'tortilla strips': null,
  'tostadas': null,
  'tri-tip': { lb: 454 },
  'turkey breast': { oz: 28, lb: 454 },
  'turmeric': null,
  'tzatziki': { tbsp: 15 },

  // ─── U ───
  'unsalted butter': { cup: 227, tbsp: 14, tsp: 5 },
  'unsweetened cocoa powder': { cup: 86, tbsp: 5 },

  // ─── V ───
  'vanilla extract': null,
  'vanilla ice cream': { cup: 140 },
  'vegetable oil': { tbsp: 14, cup: 218 },

  // ─── W ───
  'waffle cones': null,
  'waffles': null,
  'water': null,
  'water chestnuts': { cup: 140 },
  'whipped cream': null,
  'white cake': null,
  'white chocolate': { oz: 28 },
  'white chocolate chips': { cup: 168 },
  'white hominy': { cup: 165 },
  'white miso paste': { tbsp: 18 },
  'white onion': null,
  'white pepper': null,
  'white rice': { cup: 185 },
  'white vinegar': null,
  'whole milk': { cup: 244 },
  'wild rice blend': { cup: 185 },
  'wonton strips': null,
  'worcestershire sauce': null,

  // ─── Y ───
  'yakisoba noodles': { oz: 28 },
  'yellow mustard': null,
  'yellow onion': null,
  'yellow pickled radish': null,
  'yukon gold potatoes': null,

  // ─── Z ───
  'zucchini': null,
};
