/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Primary (Costco Red)
        'primary': '#ba0027',
        'primary-dim': '#a30021',
        'primary-container': '#ff7576',
        'primary-fixed': '#ff7576',
        'primary-fixed-dim': '#ff595f',
        'on-primary': '#ffefee',
        'on-primary-container': '#4e000a',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#60000f',
        'inverse-primary': '#ff525b',
        // Secondary (Buttery Yellow)
        'secondary': '#705900',
        'secondary-dim': '#624d00',
        'secondary-container': '#fdd34d',
        'secondary-fixed': '#fdd34d',
        'secondary-fixed-dim': '#eec540',
        'on-secondary': '#fff2d4',
        'on-secondary-container': '#5c4900',
        'on-secondary-fixed': '#463600',
        'on-secondary-fixed-variant': '#675200',
        // Tertiary (Orange accent)
        'tertiary': '#8a4c00',
        'tertiary-dim': '#794200',
        'tertiary-container': '#ff9727',
        'tertiary-fixed': '#ff9727',
        'tertiary-fixed-dim': '#f18900',
        'on-tertiary': '#fff0e6',
        'on-tertiary-container': '#4c2700',
        'on-tertiary-fixed': '#281200',
        'on-tertiary-fixed-variant': '#592f00',
        // Surface (Eggshell)
        'surface': '#f9f6f5',
        'surface-bright': '#f9f6f5',
        'surface-dim': '#d6d4d3',
        'surface-variant': '#dedcdc',
        'surface-tint': '#ba0027',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f0f0',
        'surface-container': '#eae8e7',
        'surface-container-high': '#e4e2e1',
        'surface-container-highest': '#dedcdc',
        // Neutral
        'on-surface': '#2f2f2f',
        'on-surface-variant': '#5c5b5b',
        'on-background': '#2f2f2f',
        'background': '#f9f6f5',
        'outline': '#787676',
        'outline-variant': '#aeadac',
        'inverse-surface': '#0e0e0e',
        'inverse-on-surface': '#9e9c9c',
        // Error
        'error': '#b02500',
        'error-dim': '#b92902',
        'error-container': '#f95630',
        'on-error': '#ffefec',
        'on-error-container': '#520c00',
      },
      fontFamily: {
        'headline': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body': ['"Be Vietnam Pro"', 'sans-serif'],
        'label': ['"Be Vietnam Pro"', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'md': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
